In [62]:
import tensorflow as tf

In [63]:
model_name = 'best_model_ever'

model = tf.keras.models.load_model(f'./{model_name}.h5')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

# Save the model.
with open(f'{model_name}.tflite', 'wb') as f:
  f.write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpgw5vsat3/assets


INFO:tensorflow:Assets written to: /tmp/tmpgw5vsat3/assets
2022-04-13 16:57:30.409020: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:363] Ignored output_format.
2022-04-13 16:57:30.409090: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:366] Ignored drop_control_dependency.
2022-04-13 16:57:30.409327: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /tmp/tmpgw5vsat3
2022-04-13 16:57:30.412562: I tensorflow/cc/saved_model/reader.cc:107] Reading meta graph with tags { serve }
2022-04-13 16:57:30.412595: I tensorflow/cc/saved_model/reader.cc:148] Reading SavedModel debug info (if present) from: /tmp/tmpgw5vsat3
2022-04-13 16:57:30.426665: I tensorflow/cc/saved_model/loader.cc:210] Restoring SavedModel bundle.
2022-04-13 16:57:30.481245: I tensorflow/cc/saved_model/loader.cc:194] Running initialization op on SavedModel bundle at path: /tmp/tmpgw5vsat3
2022-04-13 16:57:30.508321: I tensorflow/cc/saved_model/loader.cc:283] SavedMode

In [64]:
import numpy as np

In [65]:
interpreter = tf.lite.Interpreter('best_model_ever.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [66]:
inp = np.array([[[0,0,0] for _ in range(5)]], dtype='float32')
print(inp)
interpreter.set_tensor(input_details[0]['index'], inp)
interpreter.invoke()
interpreter.get_tensor(output_details[0]['index'])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


array([[0.06695357]], dtype=float32)