In [1]:
import tensorflow as tf

2022-04-20 10:34:12.116873: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-20 10:34:12.116938: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
model_name = 'contextual_model'

model = tf.keras.models.load_model(f'./{model_name}.h5')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
converter._experimental_lower_tensor_list_ops = False

tflite_model = converter.convert()

# Save the model.
with open(f'{model_name}.tflite', 'wb') as f:
  f.write(tflite_model)

2022-04-20 10:34:17.902353: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-20 10:34:17.902444: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-20 10:34:17.902501: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (penguin): /proc/driver/nvidia/version does not exist
2022-04-20 10:34:17.903078: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-20 10:34:18.227633: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but 

INFO:tensorflow:Assets written to: /tmp/tmpy9znpa1w/assets


2022-04-20 10:34:19.192792: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:363] Ignored output_format.
2022-04-20 10:34:19.192863: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:366] Ignored drop_control_dependency.
2022-04-20 10:34:19.193879: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /tmp/tmpy9znpa1w
2022-04-20 10:34:19.195583: I tensorflow/cc/saved_model/reader.cc:107] Reading meta graph with tags { serve }
2022-04-20 10:34:19.195646: I tensorflow/cc/saved_model/reader.cc:148] Reading SavedModel debug info (if present) from: /tmp/tmpy9znpa1w
2022-04-20 10:34:19.201972: I tensorflow/cc/saved_model/loader.cc:210] Restoring SavedModel bundle.
2022-04-20 10:34:19.244231: I tensorflow/cc/saved_model/loader.cc:194] Running initialization op on SavedModel bundle at path: /tmp/tmpy9znpa1w
2022-04-20 10:34:19.258254: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 64382 

In [1]:
import numpy as np

In [2]:
import tensorflow.lite as tflite

interpreter = tflite.Interpreter('best_model_ever.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

2022-04-13 18:00:52.553412: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-13 18:00:52.553466: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO: Created TensorFlow Lite delegate for select TF ops.
2022-04-13 18:00:54.668068: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-13 18:00:54.668743: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or di

In [3]:
inp = np.array([[[0,0,0] for _ in range(5)]], dtype='float32')
print(inp)
interpreter.set_tensor(input_details[0]['index'], inp)
interpreter.invoke()
interpreter.get_tensor(output_details[0]['index'])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


array([[0.06695357]], dtype=float32)